// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiaBPlCtuPvpDzU-KzRkrariAi7kOJK4I',
    appId: '1:1018694271894:web:cadbfea10de40be4f593b7',
    messagingSenderId: '1018694271894',
    projectId: 'push-notification-flutte-8cd6d',
    authDomain: 'push-notification-flutte-8cd6d.firebaseapp.com',
    storageBucket: 'push-notification-flutte-8cd6d.firebasestorage.app',
    measurementId: 'G-ZJX3LF1NKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpzTt-wLzItLN0wDC5OaWnxtUDeULG0uk',
    appId: '1:1018694271894:android:d5a9ea24b316d140f593b7',
    messagingSenderId: '1018694271894',
    projectId: 'push-notification-flutte-8cd6d',
    storageBucket: 'push-notification-flutte-8cd6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfaXUMXelNelAetontk6_-yTN2gSTuJ3w',
    appId: '1:1018694271894:ios:d1e016dc7fef2a6ff593b7',
    messagingSenderId: '1018694271894',
    projectId: 'push-notification-flutte-8cd6d',
    storageBucket: 'push-notification-flutte-8cd6d.firebasestorage.app',
    iosBundleId: 'com.example.pushMsgService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfaXUMXelNelAetontk6_-yTN2gSTuJ3w',
    appId: '1:1018694271894:ios:d1e016dc7fef2a6ff593b7',
    messagingSenderId: '1018694271894',
    projectId: 'push-notification-flutte-8cd6d',
    storageBucket: 'push-notification-flutte-8cd6d.firebasestorage.app',
    iosBundleId: 'com.example.pushMsgService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiaBPlCtuPvpDzU-KzRkrariAi7kOJK4I',
    appId: '1:1018694271894:web:ae3aa36ff98c75aaf593b7',
    messagingSenderId: '1018694271894',
    projectId: 'push-notification-flutte-8cd6d',
    authDomain: 'push-notification-flutte-8cd6d.firebaseapp.com',
    storageBucket: 'push-notification-flutte-8cd6d.firebasestorage.app',
    measurementId: 'G-NM5VCDF2R7',
  );
}
